{{- if .Values.backstage.appConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-app-config-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
data:
  app-config.yaml: {{- .Values.backstage.appConfig | toYaml | indent 2 }}
{{- end }}

{{- if .Values.sharedConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-shared-config-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
data:
  shared-config.yaml: {{- .Values.sharedConfig | toYaml | indent 2 }}
{{- end }}
