{{- if eq .Values.database.engine "postgresql" }}
---
# CNPs to allow backstage to access postgresql
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    {{- include "labels.backstage" $ | nindent 4 }}
  name: {{ .Chart.Name }}-{{ .Values.database.postgresql.clusterNameSuffix }}
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: {{ .Chart.Name }}-{{ .Values.database.postgresql.clusterNameSuffix }}
  egress:
    # Allow egress to other CNPG cluster members.
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: {{ .Chart.Name }}-{{ .Values.database.postgresql.clusterNameSuffix }}
      toPorts:
        - ports:
            - port: "5432"
    # Allow egress to world and apiserver for object storage
    - toEntities:
      - world
      - kube-apiserver
  ingress:
    - fromEndpoints:
        # Allow ingress from backstage
        - matchLabels:
            app.kubernetes.io/instance: {{ .Chart.Name }}
        # Allow ingress from other CNPG cluster members (including join pods)
        - matchLabels:
            cnpg.io/cluster: {{ .Chart.Name }}-{{ .Values.database.postgresql.clusterNameSuffix }}
      toPorts:
        - ports:
            - port: "5432"
---
# Pod monitor used to monitor the postgresql cluster. We cannot use .spec.enablePodMonitor because we cannot add the observability.giantswarm.io/tenant label
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    observability.giantswarm.io/tenant: giantswarm
    {{- include "labels.backstage" $ | nindent 4 }}
  name: {{ .Chart.Name }}-{{ .Values.database.postgresql.clusterNameSuffix }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ .Chart.Name }}-{{ .Values.database.postgresql.clusterNameSuffix }}
  podMetricsEndpoints:
  - port: metrics
---
# Postgresql cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    {{- include "labels.backstage" $ | nindent 4 }}
  name: {{ .Chart.Name }}-{{ .Values.database.postgresql.clusterNameSuffix }}
  namespace: {{ .Release.Namespace }}
spec:
  imageName: {{ .Values.registry.domain }}/{{ .Values.database.postgresql.image }}
  instances: 2
  storage:
    size: {{ .Values.database.postgresql.storageSize }}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 1Gi
    limits:
      cpu: 1000m
      memory: 512Mi
      ephemeral-storage: 2Gi
{{- end }}
