apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
stringData:
  github-app-production-credentials.yaml: {{- .Values.githubAppCredentials | toYaml | indent 1 }}
