apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.oauth2Proxy.name }}
  name: {{ .Values.oauth2Proxy.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.oauth2Proxy.name }}
  ports:
    - port: {{ .Values.oauth2Proxy.port }}
      targetPort: http
