apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.oauth2Proxy.name }}
  name: {{ .Values.oauth2Proxy.name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.oauth2Proxy.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.oauth2Proxy.name }}
    spec:
      containers:
        - name: {{ .Values.oauth2Proxy.name }}
          image: "{{ .Values.registry.domain }}/{{ .Values.oauth2Proxy.image.repository }}:{{ .Values.oauth2Proxy.version }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.oauth2Proxy.port }}
          args:
            - --provider=github
            - --github-org=giantswarm
            - --github-team=employees
            - --email-domain=*
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:{{ .Values.oauth2Proxy.port }}
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client_id
                  name: giantswarm-oauth
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client_secret
                  name: giantswarm-oauth
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  key: cookie_secret
                  name: giantswarm-oauth
          resources:
            limits:
              cpu: 300m
              memory: 20M
            requests:
              cpu: 50m
              memory: 20M
