apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
    component: oauth2-proxy
  ports:
    - port: {{ .Values.oauth2Proxy.port }}
      targetPort: http
