{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
{{- end }}
