---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
data:
  CIRCLECI_API_TOKEN: {{ .Values.circleci.apiToken }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.githubAuthCredentials.clientID }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.githubAuthCredentials.clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
data:
  client_id: {{ .Values.oauth2Proxy.secrets.client_id }}
  client_secret: {{ .Values.oauth2Proxy.secrets.client_secret }}
  cookie_secret: {{ .Values.oauth2Proxy.secrets.cookie_secret }}
