---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
data:
  {{- if .Values.authSessionSecret }}
  AUTH_SESSION_SECRET: {{ .Values.authSessionSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.clientID }}
  AUTH_DEX_CLIENT_ID: {{ .Values.dexAuthCredentials.clientID }}
  {{- end }}
  {{- if .Values.catalogLocationUrl }}
  CATALOG_LOCATION_URL: {{ .Values.catalogLocationUrl }}
  {{- end }}
  {{- if .Values.circleci.apiToken }}
  CIRCLECI_API_TOKEN: {{ .Values.circleci.apiToken }}
  {{- end }}
  {{- if .Values.githubAuthCredentials.clientID }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.githubAuthCredentials.clientID }}
  {{- end }}
  {{- if .Values.githubAuthCredentials.clientSecret }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.githubAuthCredentials.clientSecret }}
  {{- end }}
  {{- if .Values.grafana.apiToken }}
  GRAFANA_TOKEN: {{ .Values.grafana.apiToken }}
  {{- end }}
  {{- if .Values.opsgenie.apiKey }}
  OPSGENIE_API_KEY: {{ .Values.opsgenie.apiKey }}
  {{- end }}
  {{- if .Values.quay.apiToken }}
  QUAY_TOKEN  : {{ .Values.quay.apiToken }}
  {{- end }}
  {{- if .Values.sentry.app.dsn }}
  SENTRY_DSN_APP: {{ .Values.sentry.app.dsn }}
  {{- end }}
  {{- if .Values.sentry.backend.dsn }}
  SENTRY_DSN_BACKEND: {{ .Values.sentry.backend.dsn }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
stringData:
  github-app-production-credentials.yaml: {{- .Values.githubAppCredentials | toYaml | indent 2 }}
