---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" | nindent 4 }}
data:
  {{- if .Values.authSessionSecret }}
  AUTH_SESSION_SECRET: {{ .Values.authSessionSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gaggle.clientID }}
  AUTH_DEX_GAGGLE_CLIENT_ID: {{ .Values.dexAuthCredentials.gaggle.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gaggle.clientSecret }}
  AUTH_DEX_GAGGLE_CLIENT_SECRET: {{ .Values.dexAuthCredentials.gaggle.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gazelle.clientID }}
  AUTH_DEX_GAZELLE_CLIENT_ID: {{ .Values.dexAuthCredentials.gazelle.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gazelle.clientSecret }}
  AUTH_DEX_GAZELLE_CLIENT_SECRET: {{ .Values.dexAuthCredentials.gazelle.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.glippy.clientID }}
  AUTH_DEX_GLIPPY_CLIENT_ID: {{ .Values.dexAuthCredentials.glippy.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.glippy.clientSecret }}
  AUTH_DEX_GLIPPY_CLIENT_SECRET: {{ .Values.dexAuthCredentials.glippy.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.goat.clientID }}
  AUTH_DEX_GOAT_CLIENT_ID: {{ .Values.dexAuthCredentials.goat.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.goat.clientSecret }}
  AUTH_DEX_GOAT_CLIENT_SECRET: {{ .Values.dexAuthCredentials.goat.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.golem.clientID }}
  AUTH_DEX_GOLEM_CLIENT_ID: {{ .Values.dexAuthCredentials.golem.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.golem.clientSecret }}
  AUTH_DEX_GOLEM_CLIENT_SECRET: {{ .Values.dexAuthCredentials.golem.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.goose.clientID }}
  AUTH_DEX_GOOSE_CLIENT_ID: {{ .Values.dexAuthCredentials.goose.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.goose.clientSecret }}
  AUTH_DEX_GOOSE_CLIENT_SECRET: {{ .Values.dexAuthCredentials.goose.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.goten.clientID }}
  AUTH_DEX_GOTEN_CLIENT_ID: {{ .Values.dexAuthCredentials.goten.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.goten.clientSecret }}
  AUTH_DEX_GOTEN_CLIENT_SECRET: {{ .Values.dexAuthCredentials.goten.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.grizzly.clientID }}
  AUTH_DEX_GRIZZLY_CLIENT_ID: {{ .Values.dexAuthCredentials.grizzly.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.grizzly.clientSecret }}
  AUTH_DEX_GRIZZLY_CLIENT_SECRET: {{ .Values.dexAuthCredentials.grizzly.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.snail.clientID }}
  AUTH_DEX_SNAIL_CLIENT_ID: {{ .Values.dexAuthCredentials.snail.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.snail.clientSecret }}
  AUTH_DEX_SNAIL_CLIENT_SECRET: {{ .Values.dexAuthCredentials.snail.clientSecret }}
  {{- end }}
  {{- if .Values.catalogLocationUrl }}
  CATALOG_LOCATION_URL: {{ .Values.catalogLocationUrl }}
  {{- end }}
  {{- if .Values.circleci.apiToken }}
  CIRCLECI_API_TOKEN: {{ .Values.circleci.apiToken }}
  {{- end }}
  {{- if .Values.githubAuthCredentials.clientID }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.githubAuthCredentials.clientID }}
  {{- end }}
  {{- if .Values.githubAuthCredentials.clientSecret }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.githubAuthCredentials.clientSecret }}
  {{- end }}
  {{- if .Values.grafana.apiToken }}
  GRAFANA_TOKEN: {{ .Values.grafana.apiToken }}
  {{- end }}
  {{- if .Values.opsgenie.apiKey }}
  OPSGENIE_API_KEY: {{ .Values.opsgenie.apiKey }}
  {{- end }}
  {{- if .Values.quay.apiToken }}
  QUAY_TOKEN  : {{ .Values.quay.apiToken }}
  {{- end }}
  {{- if .Values.sentry.app.dsn }}
  SENTRY_DSN_APP: {{ .Values.sentry.app.dsn }}
  {{- end }}
  {{- if .Values.sentry.backend.dsn }}
  SENTRY_DSN_BACKEND: {{ .Values.sentry.backend.dsn }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" | nindent 4 }}
stringData:
  github-app-production-credentials.yaml: {{- .Values.githubAppCredentials | toYaml | indent 2 }}
