---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
data:
  {{- if .Values.aws.accessKeyID }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyID }}
  {{- end }}
  {{- if .Values.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
  {{- end }}
  {{- if .Values.authSessionSecret }}
  AUTH_SESSION_SECRET: {{ .Values.authSessionSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gaggle.clientID }}
  AUTH_DEX_GAGGLE_CLIENT_ID: {{ .Values.dexAuthCredentials.gaggle.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gaggle.clientSecret }}
  AUTH_DEX_GAGGLE_CLIENT_SECRET: {{ .Values.dexAuthCredentials.gaggle.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gazelle.clientID }}
  AUTH_DEX_GAZELLE_CLIENT_ID: {{ .Values.dexAuthCredentials.gazelle.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gazelle.clientSecret }}
  AUTH_DEX_GAZELLE_CLIENT_SECRET: {{ .Values.dexAuthCredentials.gazelle.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gcapeverde.clientID }}
  AUTH_DEX_GCAPEVERDE_CLIENT_ID: {{ .Values.dexAuthCredentials.gcapeverde.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.gcapeverde.clientSecret }}
  AUTH_DEX_GCAPEVERDE_CLIENT_SECRET: {{ .Values.dexAuthCredentials.gcapeverde.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.golem.clientID }}
  AUTH_DEX_GOLEM_CLIENT_ID: {{ .Values.dexAuthCredentials.golem.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.golem.clientSecret }}
  AUTH_DEX_GOLEM_CLIENT_SECRET: {{ .Values.dexAuthCredentials.golem.clientSecret }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.grizzly.clientID }}
  AUTH_DEX_GRIZZLY_CLIENT_ID: {{ .Values.dexAuthCredentials.grizzly.clientID }}
  {{- end }}
  {{- if .Values.dexAuthCredentials.grizzly.clientSecret }}
  AUTH_DEX_GRIZZLY_CLIENT_SECRET: {{ .Values.dexAuthCredentials.grizzly.clientSecret }}
  {{- end }}
  {{- if .Values.backendSecret }}
  BACKEND_SECRET: {{ .Values.backendSecret }}
  {{- end }}
  {{- if .Values.circleci.apiToken }}
  CIRCLECI_API_TOKEN: {{ .Values.circleci.apiToken }}
  {{- end }}
  {{- if .Values.githubAuthCredentials.clientID }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.githubAuthCredentials.clientID }}
  {{- end }}
  {{- if .Values.githubAuthCredentials.clientSecret }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.githubAuthCredentials.clientSecret }}
  {{- end }}
  {{- if .Values.grafana.apiToken }}
  GRAFANA_TOKEN: {{ .Values.grafana.apiToken }}
  {{- end }}
  {{- if .Values.quay.apiToken }}
  QUAY_TOKEN  : {{ .Values.quay.apiToken }}
  {{- end }}
  {{- if .Values.sentry.app.dsn }}
  SENTRY_DSN_APP: {{ .Values.sentry.app.dsn }}
  {{- end }}
  {{- if .Values.sentry.backend.dsn }}
  SENTRY_DSN_BACKEND: {{ .Values.sentry.backend.dsn }}
  {{- end }}
  {{- if .Values.telemetrydeck.salt }}
  TELEMETRYDECK_SALT: {{ .Values.telemetrydeck.salt }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
stringData:
  github-app-production-credentials.yaml: {{- .Values.githubAppCredentials | toYaml | indent 2 }}
