---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
data:
  {{- if .Values.aws.accessKeyID }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyID }}
  {{- end }}
  {{- if .Values.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
  {{- end }}
  {{- if .Values.authSessionSecret }}
  AUTH_SESSION_SECRET: {{ .Values.authSessionSecret }}
  {{- end }}
  {{- if .Values.circleci.apiToken }}
  CIRCLECI_API_TOKEN: {{ .Values.circleci.apiToken }}
  {{- end }}
  {{- if .Values.githubAuthCredentials.clientID }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.githubAuthCredentials.clientID }}
  {{- end }}
  {{- if .Values.githubAuthCredentials.clientSecret }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.githubAuthCredentials.clientSecret }}
  {{- end }}
  {{- if .Values.grafana.apiToken }}
  GRAFANA_TOKEN: {{ .Values.grafana.apiToken }}
  {{- end }}
  {{- if .Values.quay.apiToken }}
  QUAY_TOKEN  : {{ .Values.quay.apiToken }}
  {{- end }}
  {{- if .Values.sentry.app.dsn }}
  SENTRY_DSN_APP: {{ .Values.sentry.app.dsn }}
  {{- end }}
  {{- if .Values.sentry.backend.dsn }}
  SENTRY_DSN_BACKEND: {{ .Values.sentry.backend.dsn }}
  {{- end }}
  {{- if .Values.telemetrydeck.salt }}
  TELEMETRYDECK_SALT: {{ .Values.telemetrydeck.salt }}
  {{- end }}

{{- if .Values.githubAppCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-github-app-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
stringData:
  github-app-credentials.yaml: |
    appId: {{ .Values.githubAppCredentials.appId | quote }}
    webhookUrl: {{ .Values.githubAppCredentials.webhookUrl | quote }}
    webhookSecret: {{ .Values.githubAppCredentials.webhookSecret | quote }}
    clientId: {{ .Values.githubAppCredentials.clientId | quote }}
    clientSecret: {{ .Values.githubAppCredentials.clientSecret | quote }}
    privateKey: |
      {{- .Values.githubAppCredentials.privateKey | nindent 6 }}
{{- end }}

{{- if .Values.dexAuthCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-dex-auth-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
data:
{{- range $key, $value := .Values.dexAuthCredentials }}
  AUTH_DEX_{{ $key | snakecase | upper }}_CLIENT_ID: {{ $value.clientID }}
  AUTH_DEX_{{ $key | snakecase | upper }}_CLIENT_SECRET: {{ $value.clientSecret }}
{{- end }}
{{- end }}

{{- if .Values.pluginKeys }}
{{- range .Values.pluginKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-plugin-key-{{ .keyId }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
stringData:
  public.key: {{- .publicKey | toYaml | indent 2  }}
  private.key: {{- .privateKey | toYaml | indent 2 }}
{{- end }}
{{- end }}
