---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
data:
  CIRCLECI_API_TOKEN: {{ .Values.circleci.apiToken }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.githubAuthCredentials.clientID }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.githubAuthCredentials.clientSecret }}
  SENTRY_DSN_APP: {{ .Values.sentry.app.dsn }}
  SENTRY_DSN_BACKEND: {{ .Values.sentry.backend.dsn }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
stringData:
  github-app-production-credentials.yaml: {{- .Values.githubAppCredentials | toYaml | indent 2 }}
