---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
    component: backstage
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.port }}
      targetPort: http
