---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "labels.backstage" $ | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
  updatePolicy:
    updateMode: "Off" # We want recommendations only
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 1m
          memory: 1M
        maxAllowed:
          cpu: 2000m
          memory: 2000M
        controlledResources:
          - cpu
          - memory
