app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://portal.snail.gaws.gigantic.io

backend:
  baseUrl: https://portal.snail.gaws.gigantic.io
  listen:
    port: 7007
    host: 0.0.0.0
  cors:
    origin: https://portal.snail.gaws.gigantic.io

auth:
  environment: production
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    github:
      production:
        clientId: ${GITHUB_OAUTH_CLIENT_ID}
        clientSecret: ${GITHUB_OAUTH_CLIENT_SECRET}
    oidc-glippy:
      production:
        metadataUrl: https://dex.glippy.azuretest.gigantic.io/.well-known/openid-configuration
        clientId: ${AUTH_DEX_GLIPPY_CLIENT_ID}
        clientSecret: ${AUTH_DEX_GLIPPY_CLIENT_SECRET}
    oidc-golem:
      production:
        metadataUrl: https://dex.golem.gaws.gigantic.io/.well-known/openid-configuration
        clientId: ${AUTH_DEX_GOLEM_CLIENT_ID}
        clientSecret: ${AUTH_DEX_GOLEM_CLIENT_SECRET}
    oidc-snail:
      production:
        metadataUrl: https://dex.snail.gaws.gigantic.io/.well-known/openid-configuration
        clientId: ${AUTH_DEX_SNAIL_CLIENT_ID}
        clientSecret: ${AUTH_DEX_SNAIL_CLIENT_SECRET}
