app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://devportal.giantswarm.io
  support:
    url: https://github.com/giantswarm/giantswarm/labels/component%2Fdevportal
    items:
      - title: Issues
        icon: github
        links:
          - url: https://github.com/giantswarm/giantswarm/labels/component%2Fdevportal
            title: GitHub Issues
      - title: Slack discussion
        icon: chat
        links:
          - url: https://gigantic.slack.com/archives/C055VLMTPFE
            title: '#wg-dev-portal'

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: https://devportal.giantswarm.io
  listen:
    port: 7007
    host: 0.0.0.0
  cors:
    origin: https://devportal.giantswarm.io

  # config options: https://node-postgres.com/api/client
  database:
    client: better-sqlite3
    connection: ':memory:'
    # client: pg
    # connection:
    #   host: ${POSTGRES_HOST}
    #   port: ${POSTGRES_PORT}
    #   user: ${POSTGRES_USER}
    #   password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_OAUTH_CLIENT_ID}
        clientSecret: ${GITHUB_OAUTH_CLIENT_SECRET}

catalog:
  locations:
    - type: file
      target: /app/catalog/catalog.yaml
      rules:
        - allow: [Component, Group, User]
