backend:
  reading:
    allow:
    - host: "*.gigantic.io"

auth:
  environment: development
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    github:
      development:
        clientId: ${GITHUB_OAUTH_CLIENT_ID}
        clientSecret: ${GITHUB_OAUTH_CLIENT_SECRET}
    gs-glippy:
      development:
        metadataUrl: https://dex.glippy.azuretest.gigantic.io/.well-known/openid-configuration
        clientId: ${AUTH_DEX_GLIPPY_CLIENT_ID}
        clientSecret: ${AUTH_DEX_GLIPPY_CLIENT_SECRET}
    gs-golem:
      development:
        metadataUrl: https://dex.golem.gaws.gigantic.io/.well-known/openid-configuration
        clientId: ${AUTH_DEX_GOLEM_CLIENT_ID}
        clientSecret: ${AUTH_DEX_GOLEM_CLIENT_SECRET}
    gs-snail:
      development:
        metadataUrl: https://dex.snail.gaws.gigantic.io/.well-known/openid-configuration
        clientId: ${AUTH_DEX_SNAIL_CLIENT_ID}
        clientSecret: ${AUTH_DEX_SNAIL_CLIENT_SECRET}

gs:
  installations:
    - glippy
    - golem
    - snail

catalog:
  locations:
    - type: url
      target: https://github.com/giantswarm/github/blob/main/catalog/groups.yaml
    - type: url
      target: https://github.com/giantswarm/github/blob/main/catalog/users.yaml
