backend:
  reading:
    allow:
    - host: "*.gigantic.io"

catalog:
  locations:
    - type: url
      target: https://github.com/giantswarm/github/blob/main/catalog/groups.yaml
    - type: url
      target: https://github.com/giantswarm/github/blob/main/catalog/users.yaml
