version: '3'
services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./volumes/postgres14:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: backstage
      POSTGRES_DB: backstage
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

networks:
  external_network:
  internal_network:
    internal: true
