version: 2.1

orbs:
  architect: giantswarm/architect@4.33.1

job_filters: &job_filters
  filters:
    tags:
      only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
    branches:
      only: /.*/

whitelist: &whitelist
  paths:
    - packages/*/dist/*
    - node_modules/*
    - VERSION

image_name: &image_name quay.io/giantswarm/backstage

workflows:
  build:
    jobs:
      - build:
          <<: *job_filters
      - build-container:
          context: architect
          requires:
            - build
          <<: *job_filters
      - architect/push-to-app-catalog:
          executor: app-build-suite
          name: push-to-operations-platform-app-catalog
          context: architect
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "backstage"
          persist_chart_archive: true
          requires:
            - build-container
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          executor: app-build-suite
          name: push-to-control-plane-app-catalog
          context: architect
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "backstage"
          persist_chart_archive: true
          requires:
            - build-container
          filters:
            tags:
              only: /^v.*/

jobs:

  build:
    executor: architect/architect
    working_directory: ~/backstage
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "yarn.lock" }}
            - v2-npm-deps-
      
      - run:
          name: Print node and yarn version info
          command: |
            node --version
            yarn --version

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      
      - save_cache:
          paths:
            - node_modules
          key: v2-npm-deps-{{ checksum "yarn.lock" }}

      - run:
          name: Create VERSION file
          command: |
            echo -n "$(architect project version)" > VERSION
            echo "$(cat VERSION)"

      - run:
          name: Typecheck code using the TypeScript compiler
          command: yarn run tsc

      - run:
          name: Lint code using ESlint
          command: yarn run lint:all

      - run:
          name: Validate code style using prettier
          command: yarn run prettier:check
      
      - run:
          name: Run tests
          command: yarn run test:all
      
      - run:
          name: Mock secret files
          command: |
            touch github-app-production-credentials.yaml

      - run:
          name: Build application
          command: yarn run build:backend --config ../../app-config.yaml --config ../../app-config.production.yaml
          environment:
            NODE_ENV: production
            BACKSTAGE_ENVIRONMENT: production

      - persist_to_workspace:
          root: ~/backstage
          <<: *whitelist

  build-container:
    executor: architect/architect
    environment:
      DOCKER_BUILDKIT: "1"
    working_directory: ~/backstage
    steps:
      - checkout

      - setup_remote_docker

      - attach_workspace:
          at: ~/backstage

      - run:
          environment:
            IMAGE_NAME: *image_name
          name: Generate container image tag
          command: |
            echo -n "${IMAGE_NAME}:$(cat VERSION)" > .docker_image_name

      - architect/push-to-docker:
          tag-latest-branch: "main"
          image: "docker.io/giantswarm/backstage"
          dockerfile: 'packages/backend/Dockerfile'
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"

      - architect/push-to-docker:
          tag-latest-branch: "main"
          image: *image_name
          dockerfile: 'packages/backend/Dockerfile'
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
