---
apiVersion: example.promise.syntasso.io/v1
kind: app-deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  app: "component:giantswarm/backstage"
  cluster: "gazelle/operations"
