name: backstage
backstageDiscovery:
  kubernetesId: backstage
userID: 1000
groupID: 1000
image:
  name: backstage
  repository: giantswarm/backstage
port: 7007
registry:
  domain: gsoci.azurecr.io
authSessionSecret: Zm9vQmFy
circleci:
  apiToken: ZHVtbXlUb2tlbg==
dexAuthCredentials:
  example-1:
    clientID: ZXhhbXBsZU9uZUR1bW15Q2xpZW50SUQ=
    clientSecret: ZXhhbXBsZU9uZUR1bW15Q2xpZW50U2VjcmV0
  example-2:
    clientID: ZXhhbXBsZVR3b0R1bW15Q2xpZW50SUQ=
    clientSecret: ZXhhbXBsZVR3b0R1bW15Q2xpZW50U2VjcmV0
githubAuthCredentials:
  clientID: ZHVtbXlDbGllbnRJRA==
  clientSecret: ZHVtbXlDbGllbnRTZWNyZXQ=
githubAppCredentials:
  appId: 42
  webhookUrl: 'dummyWehbookUrl'
  webhookSecret: 'dummyWebhookSecret'
  clientId: 'dummyClientID'
  clientSecret: 'dummyClientSecret'
  privateKey: |
    dummy
    private
    key
grafana:
  apiToken: ZHVtbXlUb2tlbg==
sentry:
  app:
    dsn: c3VtbXlTZW50cnlEU04=
  backend:
    dsn: c3VtbXlTZW50cnlEU04=
backstage:
  command: ['node', 'packages/backend']
  args: []
  extraAppConfig: []
  extraEnvVars:
    - name: GLOBAL_AGENT_HTTP_PROXY
      value: http://12.34.56.78:3128
    - name: GLOBAL_AGENT_NO_PROXY
      value: 127.0.0.1,*.example.com
resources:
  verticalPodAutoscaler:
    enabled: true
  requests:
    cpu: 30m
    memory: 300M
  limits:
    cpu: 500m
    memory: 600M
database:
  engine: postgresql
  postgresql:
    clusterNameSuffix: cnpg
    image: postgresql:15
    storageSize: 10Gi

# Explicitly enable traditional Ingress (default)
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  hostnames:
    - backstage.example.com

# Explicitly disable Gateway API route
route:
  enabled: false
